name: iqa-service
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.11
  - pip==23.2.1
  - numpy==1.25.2
  - pip:
    - python-dotenv==1.0.1
    - Flask==3.1.0
    - opencv-python==4.8.1.78
    - tensorflow-cpu==2.12.0
    - pillow==10.2.0
    - scikit-image==0.22.0
    - torch==2.5.1
    - torchvision==0.20.1